# Files distributed to students (.ok & tests/ handled automatically)
sp19/lab/lab08.d: $(MATERIALS_DST)/sp19/lab/lab08/faithful.csv
sp19/lab/lab08.d: $(MATERIALS_DST)/sp19/lab/lab08/sf_salaries_2014.csv