# Files distributed to students (.ok & tests/ handled automatically)
sp19/hw/hw09.d: $(MATERIALS_DST)/sp19/hw/hw09/restaurant_inspection_scores.csv
sp19/hw/hw09.d: $(MATERIALS_DST)/sp19/hw/hw09/united_summer2015.csv