# Files distributed to students (.ok & tests/ handled automatically)
sp19/lab/lab09.d: $(MATERIALS_DST)/sp19/lab/lab09/close_novas.csv
sp19/lab/lab09.d: $(MATERIALS_DST)/sp19/lab/lab09/supernova.jpg
sp19/lab/lab09.d: $(MATERIALS_DST)/sp19/lab/lab09/drivers.csv