# Files distributed to students (.ok & tests/ handled automatically)
sp19/hw/hw10.d: $(MATERIALS_DST)/sp19/hw/hw10/triple_vertical.csv
sp19/hw/hw10.d: $(MATERIALS_DST)/sp19/hw/hw10/btc.csv
sp19/hw/hw10.d: $(MATERIALS_DST)/sp19/hw/hw10/eth.csv
sp19/hw/hw10.d: $(MATERIALS_DST)/sp19/hw/hw10/spreads.csv