# Files distributed to students (.ok & tests/ handled automatically)
sp19/project/project3.d: $(MATERIALS_DST)/sp19/project/project3/movies.csv
sp19/project/project3.d: $(MATERIALS_DST)/sp19/project/project3/proj3_test_set.csv
sp19/project/project3.d: $(MATERIALS_DST)/sp19/project/project3/stem.csv
sp19/project/project3.d: $(MATERIALS_DST)/sp19/project/project3/word_plot.png